spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/music
spring.datasource.username=postgres
spring.datasource.password=postgres

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}